import Head from 'next/head'
import { useState } from 'react'
import EventName from '../components/EventName'
import Leaderboard from '../components/Leaderboard'
import RangeSelect from '../components/RangeSelect'

export default function Home() {
  const [name, setName] = useState('')

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex justify-evenly">
          <EventName
            name={name}
            onNameChange={(e) => setName(e.target.value)}
          />
          <RangeSelect />
        </div>
        <Leaderboard name={name} />
      </main>
    </div>
  )
}
